if(MSVC)
    message(${CMAKE_GENERATOR})
    if(CMAKE_GENERATOR MATCHES "Visual Studio 12 2013")
        install (FILES "${CMAKE_CURRENT_LIST_DIR}/../openssl/winxp_x86/libeay32.dll" DESTINATION "./" OPTIONAL)
        install (FILES "${CMAKE_CURRENT_LIST_DIR}/../openssl/winxp_x86/ssleay32.dll" DESTINATION "./" OPTIONAL)
    else()
        if(CMAKE_SYSTEM_PROCESSOR STREQUAL "x86")
            install (FILES "${CMAKE_CURRENT_LIST_DIR}/../openssl/win_x86/libeay32.dll" DESTINATION "./" OPTIONAL)
            install (FILES "${CMAKE_CURRENT_LIST_DIR}/../openssl/win_x86/ssleay32.dll" DESTINATION "./" OPTIONAL)
        elseif(CMAKE_SYSTEM_PROCESSOR STREQUAL "AMD64")
            install (FILES "${CMAKE_CURRENT_LIST_DIR}/../openssl/win_x64/libeay32.dll" DESTINATION "./" OPTIONAL)
            install (FILES "${CMAKE_CURRENT_LIST_DIR}/../openssl/win_x64/ssleay32.dll" DESTINATION "./" OPTIONAL)
        endif()
    endif()
endif()
